name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/codecamp-advantage:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/codecamp-advantage:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy codecamp-advantage \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/codecamp-advantage:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
